### Get all profiles
GET https://task-tracker-minu.herokuapp.com/profiles



### Create new profile
POST https://task-tracker-minu.herokuapp.com/profiles
Content-Type: application/json

{
  "name": "Minu",
  "imageLink": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png"
}



### Update Profile
PUT https://task-tracker-minu.herokuapp.com/profiles/3
Content-Type: application/json

{
  "name": "Minu",
  "imageLink": "https://media0.faz.net/ppmedia/aktuell/politik/3269951188/1.7412920/mmobject-still_full/gesuender-oder-krank-kim-jong.jpg"
}



### Delete Profile
DELETE https://task-tracker-minu.herokuapp.com/profiles/3