### Get all profiles
GET http://localhost:4000/profiles



### Create new profile
POST http://localhost:4000/profiles
Content-Type: application/json

{
  "name": "Melissa",
  "imageLink": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png"
}



### Update Profile
PUT http://localhost:4000/profiles/1
Content-Type: application/json

{
  "name": "Lisa",
  "imageLink": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/26.png"
}



### Delete Profile
DELETE http://localhost:4000/profiles/2