### Get all tasks
GET https://task-tracker-minu.herokuapp.com/tasks



### Create new task
POST https://task-tracker-minu.herokuapp.com/tasks
Content-Type: application/json

{
  "title": "Complete me",
  "description": "Yep, exactly",
  "due": "Sunday",
  "profile": 6
}



### Update task
PUT https://task-tracker-minu.herokuapp.com/tasks/5
Content-Type: application/json

{
  "title": "New text",
  "description": "And other stuff",
  "due": "Saturday",
  "profile": 5
}




### Delete task
DELETE https://task-tracker-minu.herokuapp.com/tasks/7